/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Job {
  'id' : bigint,
  'repairNotes' : string,
  'title' : string,
  'owner' : Principal,
  'date' : string,
  'measurements' : string,
  'notes' : string,
  'photos' : Array<string>,
}
export interface Part {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'typicalUse' : string,
  'category' : string,
}
export interface Tool {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPart' : ActorMethod<[string, string, string, string], Part>,
  'addTool' : ActorMethod<[string, string, string], Tool>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJob' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    Job
  >,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deletePart' : ActorMethod<[bigint], undefined>,
  'deleteTool' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyJobs' : ActorMethod<[], Array<Job>>,
  'getParts' : ActorMethod<[], Array<Part>>,
  'getTools' : ActorMethod<[], Array<Tool>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, string, Array<string>, string],
    Job
  >,
  'updatePart' : ActorMethod<[bigint, string, string, string, string], Part>,
  'updateTool' : ActorMethod<[bigint, string, string, string], Tool>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];